# Generated by Django 4.2.27 on 2026-01-06 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meshobject',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='meshobject',
            name='prompt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
