# Generated by Django 4.2.27 on 2026-01-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_meshobject_created_at_meshobject_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meshobject',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='meshobject',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
