# Generated by Django 4.2.27 on 2026-01-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_remove_meshobject_thumbnail_url_meshobject_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meshobject',
            old_name='output_path',
            new_name='obj_path',
        ),
        migrations.AlterField(
            model_name='meshobject',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail/'),
        ),
    ]
