# Generated by Django 4.2.27 on 2026-01-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_rename_output_path_meshobject_obj_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meshobject',
            name='mlt_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='meshobject',
            name='tex_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='meshobject',
            name='obj_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
