# Generated by Django 4.2.27 on 2026-01-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_meshobject_mlt_path_meshobject_tex_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meshobject',
            name='tex_path',
        ),
        migrations.AddField(
            model_name='meshobject',
            name='tex_paths',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
