# Generated by Django 4.2.27 on 2026-01-07 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_remove_meshobject_tex_path_meshobject_tex_paths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meshobject',
            name='mlt_path',
        ),
        migrations.RemoveField(
            model_name='meshobject',
            name='tex_paths',
        ),
    ]
