# Generated by Django 4.2.27 on 2026-01-07 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_remove_meshobject_mlt_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meshobject',
            old_name='obj_path',
            new_name='folder',
        ),
    ]
